# Generated by Django 4.0.6 on 2022-07-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_Type',
            new_name='game_type',
        ),
    ]
